name: Docker Compose Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout portfolio-website-docker-compose
      uses: actions/checkout@v3

    - name: Checkout porfolio-website under ./bin/portfolio_webserver
      uses: actions/checkout@v3
      with:
        repository: sashuu69/portfolio-website
        path: ./bin/portfolio_webserver
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker Compose application
      run: docker compose build
